# Generated by Django 3.2.3 on 2021-06-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('image_icon', models.ImageField(blank=True, null=True, upload_to='category')),
                ('category_select', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='add_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('total_price', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='adding_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_category', models.CharField(max_length=50)),
                ('select_brand', models.CharField(max_length=50)),
                ('select_unit', models.CharField(max_length=50)),
                ('product_code', models.CharField(max_length=50)),
                ('product_cost', models.CharField(max_length=50)),
                ('product_sale_price', models.CharField(max_length=50)),
                ('product_alert_quantity', models.CharField(max_length=50)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('tax_type', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='addtax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=50)),
                ('tax_rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='admin_create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=40)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='index_panal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cand_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('messages', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=200)),
                ('supplier', models.CharField(max_length=100)),
                ('purchaselist', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=100)),
                ('unitprice', models.CharField(max_length=100)),
                ('subprice', models.CharField(max_length=100)),
                ('shipping', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('paidamount', models.CharField(max_length=100)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='purchase_image')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='quotation_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('product_list', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_quality', models.CharField(max_length=100)),
                ('unit_price', models.CharField(max_length=100)),
                ('sub_price', models.CharField(max_length=100)),
                ('product_describtion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='stock_transfer_adding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fwarehouse', models.CharField(max_length=100)),
                ('twarehouse', models.CharField(max_length=100)),
                ('shipping', models.CharField(max_length=100)),
                ('productlist', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=100)),
                ('unitprice', models.CharField(max_length=100)),
                ('subprice', models.CharField(max_length=100)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='staock_transfer_image')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='unitadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='useradd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('profileimage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('password', models.CharField(max_length=100)),
                ('confirmpass', models.CharField(max_length=100)),
                ('selectgroup', models.CharField(max_length=100)),
            ],
        ),
    ]
